[build]
publish = "public"
command = "hugo -v --gc --minify"
[context.production.environment]
HUGO_VERSION = "0.55.5"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
[context.split1]
command = "hugo -v --gc --minify --enableGitInfo"
[context.split1.environment]
HUGO_VERSION = "0.55.5"
HUGO_ENV = "production"
[context.deploy-preview]
command = "hugo -v --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"
[context.deploy-preview.environment]
HUGO_VERSION = "0.55.5"
[context.branch-deploy]
command = "hugo -v --gc --minify -b $DEPLOY_PRIME_URL"
[context.branch-deploy.environment]
HUGO_VERSION = "0.55.5"
[context.next.environment]
HUGO_ENABLEGITINFO = "true"